CREATE DATABASE `covid` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;

-- covid.countries definition

CREATE TABLE `countries` (
  `country_id` int NOT NULL,
  `country_name` varchar(255) NOT NULL,
  PRIMARY KEY (`country_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO covid.countries (country_id, country_name) VALUES(3, 'Afghanistan');
INSERT INTO covid.countries (country_id, country_name) VALUES(4, 'Åland Islands');
INSERT INTO covid.countries (country_id, country_name) VALUES(5, 'Albania');
INSERT INTO covid.countries (country_id, country_name) VALUES(6, 'Algeria');
INSERT INTO covid.countries (country_id, country_name) VALUES(7, 'American Samoa');
INSERT INTO covid.countries (country_id, country_name) VALUES(8, 'Andorra');
INSERT INTO covid.countries (country_id, country_name) VALUES(9, 'Angola');
INSERT INTO covid.countries (country_id, country_name) VALUES(10, 'Anguilla');
INSERT INTO covid.countries (country_id, country_name) VALUES(11, 'Antarctica');
INSERT INTO covid.countries (country_id, country_name) VALUES(12, 'Antigua and Barbuda');
INSERT INTO covid.countries (country_id, country_name) VALUES(13, 'Argentina');
INSERT INTO covid.countries (country_id, country_name) VALUES(14, 'Armenia');
INSERT INTO covid.countries (country_id, country_name) VALUES(15, 'Aruba');
INSERT INTO covid.countries (country_id, country_name) VALUES(16, 'Australia');
INSERT INTO covid.countries (country_id, country_name) VALUES(17, 'Austria');
INSERT INTO covid.countries (country_id, country_name) VALUES(18, 'Azerbaijan');
INSERT INTO covid.countries (country_id, country_name) VALUES(19, 'Bahamas (the)');
INSERT INTO covid.countries (country_id, country_name) VALUES(20, 'Bahrain');
INSERT INTO covid.countries (country_id, country_name) VALUES(21, 'Bangladesh');
INSERT INTO covid.countries (country_id, country_name) VALUES(22, 'Barbados');
INSERT INTO covid.countries (country_id, country_name) VALUES(23, 'Belarus');
INSERT INTO covid.countries (country_id, country_name) VALUES(24, 'Belgium');
INSERT INTO covid.countries (country_id, country_name) VALUES(25, 'Belize');
INSERT INTO covid.countries (country_id, country_name) VALUES(26, 'Benin');
INSERT INTO covid.countries (country_id, country_name) VALUES(27, 'Bermuda');
INSERT INTO covid.countries (country_id, country_name) VALUES(28, 'Bhutan');
INSERT INTO covid.countries (country_id, country_name) VALUES(29, 'Bolivia (Plurinational State of)');
INSERT INTO covid.countries (country_id, country_name) VALUES(30, 'Bonaire, Sint Eustatius and Saba');
INSERT INTO covid.countries (country_id, country_name) VALUES(31, 'Bosnia and Herzegovina');
INSERT INTO covid.countries (country_id, country_name) VALUES(32, 'Botswana');
INSERT INTO covid.countries (country_id, country_name) VALUES(33, 'Bouvet Island');
INSERT INTO covid.countries (country_id, country_name) VALUES(34, 'Brazil');
INSERT INTO covid.countries (country_id, country_name) VALUES(35, 'British Indian Ocean Territory (the)');
INSERT INTO covid.countries (country_id, country_name) VALUES(36, 'Brunei Darussalam');
INSERT INTO covid.countries (country_id, country_name) VALUES(37, 'Bulgaria');
INSERT INTO covid.countries (country_id, country_name) VALUES(38, 'Burkina Faso');
INSERT INTO covid.countries (country_id, country_name) VALUES(39, 'Burundi');
INSERT INTO covid.countries (country_id, country_name) VALUES(40, 'Cabo Verde');
INSERT INTO covid.countries (country_id, country_name) VALUES(41, 'Cambodia');
INSERT INTO covid.countries (country_id, country_name) VALUES(42, 'Cameroon');
INSERT INTO covid.countries (country_id, country_name) VALUES(43, 'Canada');
INSERT INTO covid.countries (country_id, country_name) VALUES(44, 'Cayman Islands (the)');
INSERT INTO covid.countries (country_id, country_name) VALUES(45, 'Central African Republic (the)');
INSERT INTO covid.countries (country_id, country_name) VALUES(46, 'Chad');
INSERT INTO covid.countries (country_id, country_name) VALUES(47, 'Chile');
INSERT INTO covid.countries (country_id, country_name) VALUES(48, 'China');
INSERT INTO covid.countries (country_id, country_name) VALUES(49, 'Christmas Island');
INSERT INTO covid.countries (country_id, country_name) VALUES(50, 'Cocos (Keeling) Islands (the)');
INSERT INTO covid.countries (country_id, country_name) VALUES(51, 'Colombia');
INSERT INTO covid.countries (country_id, country_name) VALUES(52, 'Comoros (the)');
INSERT INTO covid.countries (country_id, country_name) VALUES(53, 'Congo (the Democratic Republic of the)');
INSERT INTO covid.countries (country_id, country_name) VALUES(54, 'Congo (the)');
INSERT INTO covid.countries (country_id, country_name) VALUES(55, 'Cook Islands (the)');
INSERT INTO covid.countries (country_id, country_name) VALUES(56, 'Costa Rica');
INSERT INTO covid.countries (country_id, country_name) VALUES(57, 'Croatia');
INSERT INTO covid.countries (country_id, country_name) VALUES(58, 'Cuba');
INSERT INTO covid.countries (country_id, country_name) VALUES(59, 'Curaçao');
INSERT INTO covid.countries (country_id, country_name) VALUES(60, 'Cyprus');
INSERT INTO covid.countries (country_id, country_name) VALUES(61, 'Czechia');
INSERT INTO covid.countries (country_id, country_name) VALUES(62, 'Côte d''Ivoire');
INSERT INTO covid.countries (country_id, country_name) VALUES(63, 'Denmark');
INSERT INTO covid.countries (country_id, country_name) VALUES(64, 'Djibouti');
INSERT INTO covid.countries (country_id, country_name) VALUES(65, 'Dominica');
INSERT INTO covid.countries (country_id, country_name) VALUES(66, 'Dominican Republic (the)');
INSERT INTO covid.countries (country_id, country_name) VALUES(67, 'Ecuador');
INSERT INTO covid.countries (country_id, country_name) VALUES(68, 'Egypt');
INSERT INTO covid.countries (country_id, country_name) VALUES(69, 'El Salvador');
INSERT INTO covid.countries (country_id, country_name) VALUES(70, 'Equatorial Guinea');
INSERT INTO covid.countries (country_id, country_name) VALUES(71, 'Eritrea');
INSERT INTO covid.countries (country_id, country_name) VALUES(72, 'Estonia');
INSERT INTO covid.countries (country_id, country_name) VALUES(73, 'Eswatini');
INSERT INTO covid.countries (country_id, country_name) VALUES(74, 'Ethiopia');
INSERT INTO covid.countries (country_id, country_name) VALUES(75, 'Falkland Islands (the) [Malvinas]');
INSERT INTO covid.countries (country_id, country_name) VALUES(76, 'Faroe Islands (the)');
INSERT INTO covid.countries (country_id, country_name) VALUES(77, 'Fiji');
INSERT INTO covid.countries (country_id, country_name) VALUES(78, 'Finland');
INSERT INTO covid.countries (country_id, country_name) VALUES(79, 'France');
INSERT INTO covid.countries (country_id, country_name) VALUES(80, 'French Guiana');
INSERT INTO covid.countries (country_id, country_name) VALUES(81, 'French Polynesia');
INSERT INTO covid.countries (country_id, country_name) VALUES(82, 'French Southern Territories (the)');
INSERT INTO covid.countries (country_id, country_name) VALUES(83, 'Gabon');
INSERT INTO covid.countries (country_id, country_name) VALUES(84, 'Gambia (the)');
INSERT INTO covid.countries (country_id, country_name) VALUES(85, 'Georgia');
INSERT INTO covid.countries (country_id, country_name) VALUES(86, 'Germany');
INSERT INTO covid.countries (country_id, country_name) VALUES(87, 'Ghana');
INSERT INTO covid.countries (country_id, country_name) VALUES(88, 'Gibraltar');
INSERT INTO covid.countries (country_id, country_name) VALUES(89, 'Greece');
INSERT INTO covid.countries (country_id, country_name) VALUES(90, 'Greenland');
INSERT INTO covid.countries (country_id, country_name) VALUES(91, 'Grenada');
INSERT INTO covid.countries (country_id, country_name) VALUES(92, 'Guadeloupe');
INSERT INTO covid.countries (country_id, country_name) VALUES(93, 'Guam');
INSERT INTO covid.countries (country_id, country_name) VALUES(94, 'Guatemala');
INSERT INTO covid.countries (country_id, country_name) VALUES(95, 'Guernsey');
INSERT INTO covid.countries (country_id, country_name) VALUES(96, 'Guinea');
INSERT INTO covid.countries (country_id, country_name) VALUES(97, 'Guinea-Bissau');
INSERT INTO covid.countries (country_id, country_name) VALUES(98, 'Guyana');
INSERT INTO covid.countries (country_id, country_name) VALUES(99, 'Haiti');
INSERT INTO covid.countries (country_id, country_name) VALUES(100, 'Heard Island and McDonald Islands');
INSERT INTO covid.countries (country_id, country_name) VALUES(101, 'Holy See (the)');
INSERT INTO covid.countries (country_id, country_name) VALUES(102, 'Honduras');
INSERT INTO covid.countries (country_id, country_name) VALUES(103, 'Hong Kong');
INSERT INTO covid.countries (country_id, country_name) VALUES(104, 'Hungary');
INSERT INTO covid.countries (country_id, country_name) VALUES(105, 'Iceland');
INSERT INTO covid.countries (country_id, country_name) VALUES(106, 'India');
INSERT INTO covid.countries (country_id, country_name) VALUES(107, 'Indonesia');
INSERT INTO covid.countries (country_id, country_name) VALUES(108, 'Iran (Islamic Republic of)');
INSERT INTO covid.countries (country_id, country_name) VALUES(109, 'Iraq');
INSERT INTO covid.countries (country_id, country_name) VALUES(110, 'Ireland');
INSERT INTO covid.countries (country_id, country_name) VALUES(111, 'Isle of Man');
INSERT INTO covid.countries (country_id, country_name) VALUES(112, 'Israel');
INSERT INTO covid.countries (country_id, country_name) VALUES(113, 'Italy');
INSERT INTO covid.countries (country_id, country_name) VALUES(114, 'Jamaica');
INSERT INTO covid.countries (country_id, country_name) VALUES(115, 'Japan');
INSERT INTO covid.countries (country_id, country_name) VALUES(116, 'Jersey');
INSERT INTO covid.countries (country_id, country_name) VALUES(117, 'Jordan');
INSERT INTO covid.countries (country_id, country_name) VALUES(118, 'Kazakhstan');
INSERT INTO covid.countries (country_id, country_name) VALUES(119, 'Kenya');
INSERT INTO covid.countries (country_id, country_name) VALUES(120, 'Kiribati');
INSERT INTO covid.countries (country_id, country_name) VALUES(121, 'Korea (the Democratic People''s Republic of)');
INSERT INTO covid.countries (country_id, country_name) VALUES(122, 'Korea (the Republic of)');
INSERT INTO covid.countries (country_id, country_name) VALUES(123, 'Kuwait');
INSERT INTO covid.countries (country_id, country_name) VALUES(124, 'Kyrgyzstan');
INSERT INTO covid.countries (country_id, country_name) VALUES(125, 'Lao People''s Democratic Republic (the)');
INSERT INTO covid.countries (country_id, country_name) VALUES(126, 'Latvia');
INSERT INTO covid.countries (country_id, country_name) VALUES(127, 'Lebanon');
INSERT INTO covid.countries (country_id, country_name) VALUES(128, 'Lesotho');
INSERT INTO covid.countries (country_id, country_name) VALUES(129, 'Liberia');
INSERT INTO covid.countries (country_id, country_name) VALUES(130, 'Libya');
INSERT INTO covid.countries (country_id, country_name) VALUES(131, 'Liechtenstein');
INSERT INTO covid.countries (country_id, country_name) VALUES(132, 'Lithuania');
INSERT INTO covid.countries (country_id, country_name) VALUES(133, 'Luxembourg');
INSERT INTO covid.countries (country_id, country_name) VALUES(134, 'Macao');
INSERT INTO covid.countries (country_id, country_name) VALUES(135, 'Madagascar');
INSERT INTO covid.countries (country_id, country_name) VALUES(136, 'Malawi');
INSERT INTO covid.countries (country_id, country_name) VALUES(137, 'Malaysia');
INSERT INTO covid.countries (country_id, country_name) VALUES(138, 'Maldives');
INSERT INTO covid.countries (country_id, country_name) VALUES(139, 'Mali');
INSERT INTO covid.countries (country_id, country_name) VALUES(140, 'Malta');
INSERT INTO covid.countries (country_id, country_name) VALUES(141, 'Marshall Islands (the)');
INSERT INTO covid.countries (country_id, country_name) VALUES(142, 'Martinique');
INSERT INTO covid.countries (country_id, country_name) VALUES(143, 'Mauritania');
INSERT INTO covid.countries (country_id, country_name) VALUES(144, 'Mauritius');
INSERT INTO covid.countries (country_id, country_name) VALUES(145, 'Mayotte');
INSERT INTO covid.countries (country_id, country_name) VALUES(146, 'Mexico');
INSERT INTO covid.countries (country_id, country_name) VALUES(147, 'Micronesia (Federated States of)');
INSERT INTO covid.countries (country_id, country_name) VALUES(148, 'Moldova (the Republic of)');
INSERT INTO covid.countries (country_id, country_name) VALUES(149, 'Monaco');
INSERT INTO covid.countries (country_id, country_name) VALUES(150, 'Mongolia');
INSERT INTO covid.countries (country_id, country_name) VALUES(151, 'Montenegro');
INSERT INTO covid.countries (country_id, country_name) VALUES(152, 'Montserrat');
INSERT INTO covid.countries (country_id, country_name) VALUES(153, 'Morocco');
INSERT INTO covid.countries (country_id, country_name) VALUES(154, 'Mozambique');
INSERT INTO covid.countries (country_id, country_name) VALUES(155, 'Myanmar');
INSERT INTO covid.countries (country_id, country_name) VALUES(156, 'Namibia');
INSERT INTO covid.countries (country_id, country_name) VALUES(157, 'Nauru');
INSERT INTO covid.countries (country_id, country_name) VALUES(158, 'Nepal');
INSERT INTO covid.countries (country_id, country_name) VALUES(159, 'Netherlands (the)');
INSERT INTO covid.countries (country_id, country_name) VALUES(160, 'New Caledonia');
INSERT INTO covid.countries (country_id, country_name) VALUES(161, 'New Zealand');
INSERT INTO covid.countries (country_id, country_name) VALUES(162, 'Nicaragua');
INSERT INTO covid.countries (country_id, country_name) VALUES(163, 'Niger (the)');
INSERT INTO covid.countries (country_id, country_name) VALUES(164, 'Nigeria');
INSERT INTO covid.countries (country_id, country_name) VALUES(165, 'Niue');
INSERT INTO covid.countries (country_id, country_name) VALUES(166, 'Norfolk Island');
INSERT INTO covid.countries (country_id, country_name) VALUES(167, 'Northern Mariana Islands (the)');
INSERT INTO covid.countries (country_id, country_name) VALUES(168, 'Norway');
INSERT INTO covid.countries (country_id, country_name) VALUES(169, 'Oman');
INSERT INTO covid.countries (country_id, country_name) VALUES(170, 'Pakistan');
INSERT INTO covid.countries (country_id, country_name) VALUES(171, 'Palau');
INSERT INTO covid.countries (country_id, country_name) VALUES(172, 'Palestine, State of');
INSERT INTO covid.countries (country_id, country_name) VALUES(173, 'Panama');
INSERT INTO covid.countries (country_id, country_name) VALUES(174, 'Papua New Guinea');
INSERT INTO covid.countries (country_id, country_name) VALUES(175, 'Paraguay');
INSERT INTO covid.countries (country_id, country_name) VALUES(176, 'Peru');
INSERT INTO covid.countries (country_id, country_name) VALUES(177, 'Philippines (the)');
INSERT INTO covid.countries (country_id, country_name) VALUES(178, 'Pitcairn');
INSERT INTO covid.countries (country_id, country_name) VALUES(179, 'Poland');
INSERT INTO covid.countries (country_id, country_name) VALUES(180, 'Portugal');
INSERT INTO covid.countries (country_id, country_name) VALUES(181, 'Puerto Rico');
INSERT INTO covid.countries (country_id, country_name) VALUES(182, 'Qatar');
INSERT INTO covid.countries (country_id, country_name) VALUES(183, 'Republic of North Macedonia');
INSERT INTO covid.countries (country_id, country_name) VALUES(184, 'Romania');
INSERT INTO covid.countries (country_id, country_name) VALUES(185, 'Russian Federation (the)');
INSERT INTO covid.countries (country_id, country_name) VALUES(186, 'Rwanda');
INSERT INTO covid.countries (country_id, country_name) VALUES(187, 'Réunion');
INSERT INTO covid.countries (country_id, country_name) VALUES(188, 'Saint Barthélemy');
INSERT INTO covid.countries (country_id, country_name) VALUES(189, 'Saint Helena, Ascension and Tristan da Cunha');
INSERT INTO covid.countries (country_id, country_name) VALUES(190, 'Saint Kitts and Nevis');
INSERT INTO covid.countries (country_id, country_name) VALUES(191, 'Saint Lucia');
INSERT INTO covid.countries (country_id, country_name) VALUES(192, 'Saint Martin (French part)');
INSERT INTO covid.countries (country_id, country_name) VALUES(193, 'Saint Pierre and Miquelon');
INSERT INTO covid.countries (country_id, country_name) VALUES(194, 'Saint Vincent and the Grenadines');
INSERT INTO covid.countries (country_id, country_name) VALUES(195, 'Samoa');
INSERT INTO covid.countries (country_id, country_name) VALUES(196, 'San Marino');
INSERT INTO covid.countries (country_id, country_name) VALUES(197, 'Sao Tome and Principe');
INSERT INTO covid.countries (country_id, country_name) VALUES(198, 'Saudi Arabia');
INSERT INTO covid.countries (country_id, country_name) VALUES(199, 'Senegal');
INSERT INTO covid.countries (country_id, country_name) VALUES(200, 'Serbia');
INSERT INTO covid.countries (country_id, country_name) VALUES(201, 'Seychelles');
INSERT INTO covid.countries (country_id, country_name) VALUES(202, 'Sierra Leone');


-- covid.covidstats definition

CREATE TABLE `covidstats` (
  `id` int NOT NULL,
  `action_type` varchar(255) NOT NULL,
  `country` varchar(255) NOT NULL,
  `date` date NOT NULL,
  `figure` varchar(255) NOT NULL,
  `region` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


INSERT INTO covid.covidstats (id, action_type, country, `date`, figure, region) VALUES(276, 'New Cases', 'India', '2021-05-15', '5000', 'Delhi');
INSERT INTO covid.covidstats (id, action_type, country, `date`, figure, region) VALUES(277, 'New Cases', 'India', '2021-05-14', '4500', 'Delhi');
INSERT INTO covid.covidstats (id, action_type, country, `date`, figure, region) VALUES(278, 'New Cases', 'India', '2021-05-13', '6500', 'Delhi');
INSERT INTO covid.covidstats (id, action_type, country, `date`, figure, region) VALUES(279, 'New Cases', 'India', '2021-05-12', '9000', 'Delhi');
INSERT INTO covid.covidstats (id, action_type, country, `date`, figure, region) VALUES(280, 'New Cases', 'India', '2021-05-11', '8000', 'Delhi');
INSERT INTO covid.covidstats (id, action_type, country, `date`, figure, region) VALUES(281, 'New Cases', 'India', '2021-05-10', '8900', 'Delhi');
INSERT INTO covid.covidstats (id, action_type, country, `date`, figure, region) VALUES(282, 'New Cases', 'India', '2021-05-09', '6783', 'Delhi');
INSERT INTO covid.covidstats (id, action_type, country, `date`, figure, region) VALUES(283, 'New Cases', 'India', '2021-05-16', '45000', 'Bihar');
INSERT INTO covid.covidstats (id, action_type, country, `date`, figure, region) VALUES(284, 'New Cases', 'India', '2021-05-15', '7800', 'Bihar');
INSERT INTO covid.covidstats (id, action_type, country, `date`, figure, region) VALUES(285, 'New Cases', 'India', '2021-05-14', '4589', 'Bihar');
INSERT INTO covid.covidstats (id, action_type, country, `date`, figure, region) VALUES(286, 'New Cases', 'India', '2021-05-13', '2456', 'Bihar');
INSERT INTO covid.covidstats (id, action_type, country, `date`, figure, region) VALUES(287, 'New Cases', 'India', '2021-05-12', '7893', 'Bihar');
INSERT INTO covid.covidstats (id, action_type, country, `date`, figure, region) VALUES(288, 'New Cases', 'India', '2021-05-11', '78951', 'Bihar');
INSERT INTO covid.covidstats (id, action_type, country, `date`, figure, region) VALUES(289, 'New Cases', 'India', '2021-05-10', '8500', 'Bihar');
INSERT INTO covid.covidstats (id, action_type, country, `date`, figure, region) VALUES(290, 'New Cases', 'India', '2021-05-09', '7654', 'Bihar');
INSERT INTO covid.covidstats (id, action_type, country, `date`, figure, region) VALUES(291, 'New Cases', 'India', '2021-05-17', '80000', 'Bihar');
INSERT INTO covid.covidstats (id, action_type, country, `date`, figure, region) VALUES(292, 'New Cases', 'India', '2021-05-16', '6002', 'Delhi');
INSERT INTO covid.covidstats (id, action_type, country, `date`, figure, region) VALUES(295, 'Deaths', 'India', '2021-05-17', '10000', 'Delhi');
INSERT INTO covid.covidstats (id, action_type, country, `date`, figure, region) VALUES(296, 'New Cases', 'India', '2021-05-08', '12099', 'Delhi');
INSERT INTO covid.covidstats (id, action_type, country, `date`, figure, region) VALUES(297, 'New Cases', 'India', '2021-05-07', '12345', 'Delhi');
INSERT INTO covid.covidstats (id, action_type, country, `date`, figure, region) VALUES(298, 'New Cases', 'India', '2021-05-06', '89007', 'Delhi');
INSERT INTO covid.covidstats (id, action_type, country, `date`, figure, region) VALUES(299, 'New Cases', 'India', '2021-05-05', '9800', 'Delhi');
INSERT INTO covid.covidstats (id, action_type, country, `date`, figure, region) VALUES(300, 'New Cases', 'India', '2021-05-04', '6700', 'Delhi');
INSERT INTO covid.covidstats (id, action_type, country, `date`, figure, region) VALUES(301, 'New Cases', 'India', '2021-05-03', '4500', 'Delhi');
INSERT INTO covid.covidstats (id, action_type, country, `date`, figure, region) VALUES(302, 'New Cases', 'India', '2021-05-02', '34556', 'Delhi');
INSERT INTO covid.covidstats (id, action_type, country, `date`, figure, region) VALUES(303, 'New Cases', 'India', '2021-05-01', '5643', 'Delhi');
INSERT INTO covid.covidstats (id, action_type, country, `date`, figure, region) VALUES(304, 'New Cases', 'India', '2021-04-30', '34241', 'Delhi');
INSERT INTO covid.covidstats (id, action_type, country, `date`, figure, region) VALUES(305, 'New Cases', 'India', '2021-04-29', '1234432', 'Delhi');
INSERT INTO covid.covidstats (id, action_type, country, `date`, figure, region) VALUES(306, 'Tests', 'India', '2021-05-17', '67000', 'Delhi');
INSERT INTO covid.covidstats (id, action_type, country, `date`, figure, region) VALUES(307, 'Vaccination', 'India', '2021-05-17', '93000', 'Delhi');
INSERT INTO covid.covidstats (id, action_type, country, `date`, figure, region) VALUES(308, 'New Cases', 'India', '2021-04-26', '7890', 'Delhi');
INSERT INTO covid.covidstats (id, action_type, country, `date`, figure, region) VALUES(309, 'New Cases', 'India', '2021-05-18', '15000', 'Delhi');
INSERT INTO covid.covidstats (id, action_type, country, `date`, figure, region) VALUES(310, 'New Cases', 'India', '2021-05-17', '12000', 'Delhi');
INSERT INTO covid.covidstats (id, action_type, country, `date`, figure, region) VALUES(311, 'New Cases', 'India', '2025-02-10', '12000', 'Kerala');
